#!/bin/bash
git diff --quiet && (
    VERSION=0.1.`git log --oneline | grep -v 'Bump version to' | wc -l` &&
    echo Bumping version to $VERSION &&
    sed -i -e "s/__version__.*/__version__ = '$VERSION'/" flask_mwoauth/__init__.py  &&
    vim CHANGELOG.rst +3 -c ':read !echo'" -e '\n\nv$VERSION (`date`)\n========================================'"
    vim CREDITS.rst
    git add CHANGELOG.rst CREDITS.rst
    git commit flask_mwoauth/__init__.py -m "Bump version to $VERSION" &&
    git tag $VERSION HEAD && 
    git push &&
    python setup.py sdist upload
) || (
    echo "Working copy must be clean"
)
